import Head from "next/head";
import { NextPageWithLayout } from "../../types/nextPageWithLayout";
import LayoutSignForm from "../../components/LayoutSignForm";
import SignUpForm from "../../components/SignIn/SignUpForm";

const SignUp: NextPageWithLayout = () => {
  return (
    <>
      <Head>
        <title>Fleekshot</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <SignUpForm />
    </>
  );
};

SignUp.getLayout = function getLayout(page) {
  return <LayoutSignForm>{page}</LayoutSignForm>;
};

export default SignUp;
