import Head from "next/head";
import { NextPageWithLayout } from "../../types/nextPageWithLayout";
import LayoutSignForm from "../../components/LayoutSignForm";
import SignInForm from "../../components/SignInForm";

const SignIn: NextPageWithLayout = () => {
  return (
    <>
      <Head>
        <title>Fleekshot</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <SignInForm />
    </>
  );
};

SignIn.getLayout = function getLayout(page) {
  return <LayoutSignForm>{page}</LayoutSignForm>;
};

export default SignIn;
