import Head from "next/head";
import { NextPageWithLayout } from "../../types/nextPageWithLayout";
import LayoutSignup from "../../components/LayoutSignup";
import TextField from "../../components/forms/Textfield/components/TextField";

const Signup: NextPageWithLayout = () => {
  return (
    <>
      <Head>
        <title>Fleekshot</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <div>
        <TextField id="text" type="text" label="First input" />
      </div>
    </>
  );
};

Signup.getLayout = function getLayout(page) {
  return <LayoutSignup>{page}</LayoutSignup>;
};

export default Signup;
