import Head from "next/head";
import { NextPageWithLayout } from "../../types/nextPageWithLayout";
import LayoutSignup from "../../components/LayoutSignup";
import SignupForm from "../../components/SignupForm";

const Signup: NextPageWithLayout = () => {
  return (
    <>
      <Head>
        <title>Fleekshot</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <SignupForm />
    </>
  );
};

Signup.getLayout = function getLayout(page) {
  return <LayoutSignup>{page}</LayoutSignup>;
};

export default Signup;
