import { NextPageContext } from "next";
import Head from "next/head";
import Link from "next/link";
import { FormattedMessage } from "react-intl";
import Layout from "../components/Layout";
import UtilsLinks from "../components/Layout/components/UtilsLinks";
import protectRoute from "../components/Layout/utils/protectRoute";
import { NextPageWithLayout } from "../types/nextPageWithLayout";

const Home: NextPageWithLayout = () => {
  return (
    <>
      <Head>
        <title>Fleekshot</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <UtilsLinks />
      </div>
    </>
  );
};

Home.getLayout = function getLayout(page) {
  return <Layout>{page}</Layout>;
};

export default protectRoute(Home);
