import type { NextPage } from "next";
import Head from "next/head";
import { FormattedMessage } from "react-intl";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Fleekshot</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <FormattedMessage id="hello" />
      </div>
    </>
  );
};

export default Home;
